// <auto-generated />
using System;
using DelMazo.PointRecord.Service.PersistenceDb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DelMazo.PointRecord.Service.PersistenceDb.Migrations
{
    [DbContext(typeof(PointRecordContext))]
    partial class PointRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DelMazo.PointRecord.Service.Domain.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("DelMazo.PointRecord.Service.Domain.Entities.PunchClock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishWork")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartWork")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("PunchClock");
                });
#pragma warning restore 612, 618
        }
    }
}
